---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: alertmanager-pv-claim
  labels:
    app: alertmanager
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: gold
