apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: "{{ .Release.Service }}"
    release: "{{ .Release.Name }}"
  name: {{ template "fullname" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: kafka
      port: {{ .Values.service.port }}
      targetPort: kafka
  selector:
    app: {{ template "fullname" . }}
