exporter:
  enabled: false
  image:
    repository: rbrndt/kafka-prometheus
    tag: latest
    pullPolicy: IfNotPresent
  port: 7204
watcher:
  enabled: false
  image:
    repository: monasca/kafka-watcher
    tag: 0.0.4
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 32Mi
      cpu: 25m
    limits:
      memory: 64Mi
      cpu: 50m
  port: 8080
  health_check_topic: kafka-health-check
  group_id: kafka_watcher
  watcher_period: 600
  watcher_timeout: 60
  stay_alive_on_failure: false
image:
  repository: monasca/kafka
  tag: 0.9.0.1-2.11-1.1.6
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 9092
resources:
  requests:
    memory: 1Gi
    cpu: 250m
  limits:
    memory: 2Gi
    cpu: 2000m
persistence:
  storageClass: default
  enabled: false
  accessMode: ReadWriteOnce
  size: 10Gi
memory_ratio: .85
stack_size: 1024k
stay_alive_on_failure: false
init:
  enabled: true
  image:
    repository: monasca/kafka-init
    tag: 0.0.3
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 128Mi
      cpu: 200m
    limits:
      memory: 256Mi
      cpu: 250m
  topicConfig: ''
  topics: []
static_service:
  enabled: false
  type: ClusterIP
  name: kafka
  port: 9092

zookeeper:
  overrideUri: ''

cleanup:
  name: cleanup
  serviceAccount: ''
  image:
    repository: monasca/job-cleanup
    tag: 1.2.1
    pullPolicy: IfNotPresent
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 128Mi
      cpu: 100m
  wait:
    retries: "24"
    delay: "5.0"
    timeout: "10"

rbac:
  create: false
