---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: openstack-exporter-svc
  labels:
    app: openstack-exporter
spec:
  ports:
  - name: metrics
    port: 9180
    targetPort: metrics
  selector:
    app: openstack-exporter
