---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: openstack-exporter
  labels:
    app: openstack-exporter
spec:
  selector:
    matchLabels:
      app: openstack-exporter
  template:
    metadata:
      labels:
        app: openstack-exporter
    spec:
      containers:
      - name: openstack-exporter
        image: quay.io/niedbalski/openstack-exporter-linux-amd64:master
        args:
        - --endpoint-type=public
        - default
        volumeMounts:
          - name: openstack-config
            mountPath: /etc/openstack
        ports:
        - name: metrics
          containerPort: 9180
      volumes:
        - configMap:
            defaultMode: 420
            name: openstack-conf
          name: openstack-config

