kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global: {}
    #   receivers:
    #- name: default-receiver
    route:
      group_interval: 5m
      group_wait: 10s
      #receiver: default-receiver
      repeat_interval: 3h
      receiver: 'email'
    receivers:
    - name: 'email'
      email_configs:
      - to: 'cloud.operation@brilliant.com.bd'
        from: 'monitor@brilliant.com.bd'
        smarthost: mta.brilliant.com.bd:25
        auth_username: 'monitor@brilliant.com.bd'
        auth_identity: 'monitor@brilliant.com.bd'
        auth_password: 'Cl0ud-M0n!t0r'
    inhibit_rules:
     - source_match:
        severity: 'critical'
       target_match:
        severity: 'warning'
       equal: ['alertname', 'dev', 'instance']          
