apiVersion: v1
data:
  prometheus.yml: |+
    global:
      scrape_interval: 10s

    rule_files:
      - /etc/prometheus/rules.yml


    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            # Alertmanager's default port is 9093
            - alertmanager:9093

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'ceph'
        static_configs:
          - targets: ['118.67.220.34:9283']
    #  - job_name: 'node-exporter'
    #    static_configs:
    #      - targets: ['localhost:9100']

kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring

