apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  namespace: monitoring
spec:
  ports:
  - name: service
    port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: prometheus

