apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"batch/v1","kind":"Job","metadata":{"annotations":{},"labels":{"app":"monasca-grafana","component":"grafana-init-job"},"name":"monasca-grafana-init-job","namespace":"monasca"},"spec":{"template":{"metadata":{"labels":{"app":"monasca-grafana","component":"grafana-init-job"}},"spec":{"containers":[{"env":[{"name":"LOG_LEVEL","value":"DEBUG"},{"name":"GRAFANA_URL","value":"http://monasca-grafana:3000"},{"name":"GRAFANA_USERNAME","value":"monasca-agent"},{"name":"GRAFANA_PASSWORD","value":"password"},{"name":"DATASOURCE_URL","value":"http://monasca-api:8070/"}],"image":"monasca/grafana-init","imagePullPolicy":"IfNotPresent","name":"grafana-init-job"}],"restartPolicy":"OnFailure"}}}}
  labels:
    app: monasca-grafana
    component: grafana-init-job
  name: monasca-grafana-init-job
  namespace: monasca
spec:
  backoffLimit: 6
  completions: 1
  parallelism: 1
  template:
    metadata:
      labels:
        app: monasca-grafana
        component: grafana-init-job
        job-name: monasca-grafana-init-job
    spec:
      containers:
      - env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: GRAFANA_URL
          value: http://monasca-grafana:3000
        - name: GRAFANA_USERNAME
          value: monasca-agent
        - name: GRAFANA_PASSWORD
          value: password
        - name: DATASOURCE_URL
          value: http://monasca-api:8070/
        image: monasca/grafana-init
        imagePullPolicy: IfNotPresent
        name: grafana-init-job
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
